version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - '3000:3000'
    # environment:
      # - NODE_ENV=production - dont put this causes issue
    # depends_on:
    #   - postgres
  # postgres:
  #   image: postgres:10
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase